# Generated by Django 2.2 on 2021-03-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('position', models.CharField(max_length=32, verbose_name='职位')),
                ('company', models.CharField(choices=[('1', '深圳总公司'), ('2', '武汉分公司'), ('1', '北京分公司')], max_length=32)),
                ('phone', models.CharField(max_length=11, verbose_name='联系方式')),
                ('creat_time', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('last_time', models.DateField(auto_now=True, null=True, verbose_name='最后一次登录时间')),
            ],
        ),
    ]
