# Generated by Django 2.2 on 2021-03-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210323_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default='test', max_length=256, verbose_name='文章摘要'),
            preserve_default=False,
        ),
    ]
