# Generated by Django 2.2 on 2021-03-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_article_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_status',
            field=models.BooleanField(choices=[(False, '未发布'), (True, '已发布')], default=False, verbose_name='发布状态'),
        ),
    ]
