# Generated by Django 2.2 on 2021-03-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_article_publish_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='image/profile/default/jpg', upload_to='image/profile', verbose_name='头像'),
        ),
    ]
